#! /bin/zsh

# run raskell inside of rlwrap
# rlwrap (read-line wrapper) is a linux utility that handles the annoying 
# parts of making a REPL (dealing with backspace, delete, arrow keys, 
# command history access via up arrow, etc.)
rlwrap ./raskell
